In [2]:
import pandas as pd
df = pd.read_csv("loan.csv")
df

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,4265,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,4266,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,4267,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [4]:
df.columns = df.columns.str.strip()

In [5]:
print(df.columns)

Index(['loan_id', 'no_of_dependents', 'education', 'self_employed',
       'income_annum', 'loan_amount', 'loan_term', 'cibil_score',
       'residential_assets_value', 'commercial_assets_value',
       'luxury_assets_value', 'bank_asset_value', 'loan_status'],
      dtype='str')

In [6]:
df["total_assets"] =(
    df["residential_assets_value"]
    + df["commercial_assets_value"]
    + df["luxury_assets_value"]
    + df["bank_asset_value"]
)
df['total_assets']

0       50700000
1       17000000
2       57700000
3       52700000
4       55000000
          ...
4264     7400000
4265    20000000
4266    39000000
4267    28800000
4268    77300000
Name: total_assets, Length: 4269, dtype: int64

In [7]:
print(df.head())

   loan_id  no_of_dependents      education self_employed  income_annum  \
0        1                 2       Graduate            No       9600000
1        2                 0   Not Graduate           Yes       4100000
2        3                 3       Graduate            No       9100000
3        4                 3       Graduate            No       8200000
4        5                 5   Not Graduate           Yes       9800000

   loan_amount  loan_term  cibil_score  residential_assets_value  \
0     29900000         12          778                   2400000
1     12200000          8          417                   2700000
2     29700000         20          506                   7100000
3     30700000          8          467                  18200000
4     24200000         20          382                  12400000

   commercial_assets_value  luxury_assets_value  bank_asset_value loan_status  \
0                 17600000             22700000           8000000    Approved
1                  2200000              8800000           3300000    Rejected
2                  4500000             33300000          12800000    Rejected
3                  3300000             23300000           7900000    Rejected
4                  8200000             29400000           5000000    Rejected

   total_assets
0      50700000
1      17000000
2      57700000
3      52700000
4      55000000

In [8]:
data = {
    "income": df["income_annum"],
    "loan_amount": df["loan_amount"],
    "loan_term": df["loan_term"],
    "creditscore": df["cibil_score"],
    "total_assets": df["total_assets"],
    "loan_status": df["loan_status"]
}

df = pd.DataFrame(data)
df

       income  loan_amount  loan_term  creditscore  total_assets loan_status
0     9600000     29900000         12          778      50700000    Approved
1     4100000     12200000          8          417      17000000    Rejected
2     9100000     29700000         20          506      57700000    Rejected
3     8200000     30700000          8          467      52700000    Rejected
4     9800000     24200000         20          382      55000000    Rejected
...       ...          ...        ...          ...           ...         ...
4264  1000000      2300000         12          317       7400000    Rejected
4265  3300000     11300000         20          559      20000000    Approved
4266  6500000     23900000         18          457      39000000    Rejected
4267  4100000     12800000          8          780      28800000    Approved
4268  9200000     29700000         10          607      77300000    Approved

[4269 rows x 6 columns]

In [13]:
#input
# x = df[['income', 'loan_amount', 'loan_term', 'total_assets']]
#
# #target
# y= df[['creditscore']]

x = df[['income', 'loan_amount', 'loan_term', 'total_assets']]

y = df['creditscore']


#
# model = LogisticRegression()
#
# model = LogisticRegression()
#
# model.fit(x, y)

print("downloading.......\n")


income = float(input("Enter Annual Income: "))
loan_amount = float(input("Enter Loan Amount: "))
loan_term = int(input("Enter Loan Term (months): "))
# creditscore = int(input("Enter CIBIL Score: "))
total_assets = float(input("Enter Total Assets: "))

print("Income What You Earn :- ", income)
print("Loan Amount :- ", loan_amount)
print("Loan Term :- ", loan_term)
print("Total Assets You Have :- ", total_assets)


from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(x, y)



prediction = model.predict([[income,loan_amount,loan_term,total_assets]])

print("predicted cibil score :- ", round(prediction[0]))

downloading.......

Income What You Earn :-  10101010.0
Loan Amount :-  101010.0
Loan Term :-  10
Total Assets You Have :-  5.0
predicted cibil score :-  584

C:\Users\HP\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(